In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

Sequential = tf.keras.models.Sequential
LSTM = tf.keras.layers.LSTM
Dense = tf.keras.layers.Dense

c:\users\karol\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\karol\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\karol\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\karol\appd

In [2]:
def split_sequence(sequence, n_steps):
    X, y = [], []
    for i in range(len(sequence)):
        end_ix = i + n_steps
        if end_ix > len(sequence) - 1:
            break
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [3]:
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
n_steps = 3
X, y = split_sequence(raw_seq, n_steps)
print(X)
print(y)
for i in range(len(X)):
    print(f"{X[i]} -> {y[i]}")

[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]]
[40 50 60 70 80 90]
[10 20 30] -> 40
[20 30 40] -> 50
[30 40 50] -> 60
[40 50 60] -> 70
[50 60 70] -> 80
[60 70 80] -> 90


In [4]:
X.shape

(6, 3)

In [5]:
Sequential = tf.keras.models.Sequential
LSTM = tf.keras.layers.LSTM
Dense = tf.keras.layers.Dense

In [6]:
n_features = 1
print((X.shape[0], X.shape[1], n_features))
X = X.reshape((X.shape[0], X.shape[1], n_features))
X

(6, 3, 1)


array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]]])

https://medium.com/@shivajbd/understanding-input-and-output-shape-in-lstm-keras-c501ee95c65e

First dimension represents the __batch size__, the second dimension represents the number of __time-steps__ you are feeding a sequence. And the third dimension represents the number of __units__ in one input sequence. For example, the input shape looks like __(batch_size, time_steps, seq_len)__

Czyli:

__batch_size__ to ile chcemy dać próbek

__time_stamps__ to ilość elementów po sobie w czasie

__seq_len__ to ilość wyników, featursów do przewidzenia

__input_shape__ wygląda jak 2D tablica, ale tak naprawdę to tablica 3d  
the number of time steps is __n_steps__ and the number of input units is __n_features__. And you can give any size for a batch. So our input array shape looks like (batch_size, 2, 10).
https://machinelearningmastery.com/adam-optimization-algorithm-for-deep-learning/

In [7]:
model = Sequential()
model.add(LSTM(50, activation="relu", input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

W0926 19:46:21.752573 13376 deprecation.py:506] From c:\users\karol\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [8]:
print(X, y)
model.fit(X, y, epochs=200, verbose=0)

W0926 19:46:22.001904 13376 deprecation.py:323] From c:\users\karol\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


[[[10]
  [20]
  [30]]

 [[20]
  [30]
  [40]]

 [[30]
  [40]
  [50]]

 [[40]
  [50]
  [60]]

 [[50]
  [60]
  [70]]

 [[60]
  [70]
  [80]]] [40 50 60 70 80 90]


In [9]:
x_input = np.array([700,800,900]).reshape((1, n_steps, n_features))
print(x_input)
yhat = model.predict(x_input, verbose=0)

[[[700]
  [800]
  [900]]]


In [10]:
wynik = float(yhat[0])
print(wynik)

1058.3463134765625
